
#define BSP_BTN_BLE_ENABLED 1
#define BLE_ADVERTISING_ENABLED 1
#define NRF_BLE_CONN_PARAMS_ENABLED 1
#define NRF_SDH_BLE_PERIPHERAL_LINK_COUNT 1
#define NRF_BLE_GATT_ENABLED 1
#define GPIOTE_ENABLED 1
#define FDS_ENABLED 1
#define PEER_MANAGER_ENABLED 1
#define BLE_NUS_ENABLED 1
#define NRF_FSTORAGE_ENABLED 1

#define TWI_ENABLED 1
#define TWI0_ENABLED 1
#define TWI0_USE_EASY_DMA 1

#define TIMER_ENABLED 1
#define TIMER0_ENABLED 1
#define APP_TIMER_ENABLED 1

#define APP_UART_ENABLED 1
#define UART_ENABLED 1
#define APP_FIFO_ENABLED 1

#define BUTTON_ENABLED 1

#define NRF_CLI_ENABLED 1
#define NRF_LOG_BACKEND_UART_ENABLED 1
#define NRF_LOG_BACKEND_RTT_ENABLED 1
#define NRF_LOG_ENABLED 1
#define NRF_LOG_DEFERRED 1
#define NRF_SDH_BLE_LOG_ENABLED 1
#define NRF_SDH_LOG_ENABLED 1
#define NRF_SDH_SOC_LOG_ENABLED 1

#define NRF_SDH_BLE_ENABLED 1
#define NRF_SDH_ENABLED 1
#define NRF_SDH_SOC_ENABLED 1

#define NRF_BALLOC_ENABLED 1
#define NRF_FPRINTF_ENABLED 1
#define NRF_MEMOBJ_ENABLED 1
#define NRF_SECTION_ITER_ENABLED 1
#define NRF_STRERROR_ENABLED 1

